language: python

python:
    - "3.6"

env:
    - pip install -r requirements.txt

sudo: false

install:
    # pylint,flake8: static analysis and style checks against PEP8
    - pip install -U pylint_runner
    - pip install -U flake8

script:
    # Static analysis
    - pylint_runner
    - flake8 .
